// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return $('h1,h2,h3,li,p').each(function() {
      return $(this).html($(this).html().replace(/\s([^\s<]+)\s*$/, "&nbsp;$1"));
    });
  });

}).call(this);
